### ISSUE TITLE
Support `-4`(`--ipv4`) and `-6`(`--ipv6`) flags

### ISSUE THREAD

**Issue by sfionov** [ameshkov/gocurl#25]
It is useful when it is needed to test availability of some site via IPv6/IPv4 only

**Comment by ameshkov** [comment]
Btw, it seems `curl` does that on the DNS resolution level and ignores for the case when there's no resolution:
`curl -v -I --ipv6 https://1.1.1.1`

Not sure if that's the correct behavior tbh.
