### ISSUE TITLE
Add new --dns-servers command-line argument with DoT/DoQ/DoH support

### ISSUE THREAD

**Issue by ameshkov** [ameshkov/gocurl#6]
curl does not provide it, but IMO it makes sense to be able to specify concrete DNS server that will be used.

**Comment by Snawoot** [comment]
Makes sense, especially in conjunction with ECH.

Side note: `curl` does support `--dns-servers` option as long as it was built with c-ares support. Same is true for `wget`.

**Comment by Snawoot** [comment]
Great!
